"""Answers one assistant chat turn in the configured mode.

The three modes differ in what the model is given and what it may do:

- ``workflow``: the code fetches the documents and, when the request names a project, the
  project, its result and its opinions, and the model makes one call with no tools.
- ``hybrid``: the same, except the opinions, and the model may then call the tools.
- ``agent``: nothing is fetched ahead; the model calls the tools.

The system prompt is :data:`~api.assistant.agent.prompt.SYSTEM_PROMPT`, unchanged, in every
mode. What is fetched goes into the user message, ahead of the question, and when the
question is recognisably Czech or English the message ends with a line that states the answer
language (see :func:`~api.assistant.agent.generation.user_message`).
"""

import asyncio
import logging
from collections.abc import AsyncGenerator
from dataclasses import dataclass

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, AnyMessage, HumanMessage

from api.assistant.agent.checks import check_citations, find_ungrounded_numbers, strip_citations
from api.assistant.agent.context import AssistantContext
from api.assistant.agent.generation import (
    AgentGenerator,
    AnswerGenerator,
    CutOffAnswerError,
    DirectGenerator,
    Generated,
    user_message,
)
from api.assistant.agent.prompt import (
    FORMULA_NUMBERS,
    PINNED_NUMBERS,
    render_context_block,
)
from api.assistant.agent.tools import render_opinions, render_project
from api.assistant.agent.tracing import tracing_scope
from api.assistant.errors import AssistantNotFoundError, AssistantUnavailableError
from api.assistant.upstream import UNAVAILABLE_ERRORS
from api.config import Settings
from api.exceptions import ProjectNotFoundError
from api.schemas.assistant import (
    AnswerChecks,
    AssistantChatRequest,
    AssistantChatResponse,
    ChatTurn,
    TurnTiming,
)

logger = logging.getLogger(__name__)

# The most characters of history the model is sent. The answer model's window is 16384
# tokens, and this budget is what keeps the worst case inside it: the history is the part
# of the prompt the client controls, so the fetched context, the message and the answer
# are left room by capping it.
_HISTORY_CHAR_BUDGET = 6000


def _kept_history(history: list[ChatTurn], max_turns: int) -> list[ChatTurn]:
    """Choose the part of the client's history the model is sent.

    The history comes from the client, so an ``assistant`` entry is the user's own input
    like any other: it gives them nothing they could not type directly. Earlier answers
    still go through :func:`~api.assistant.agent.checks.strip_citations`, because their
    ``[n]`` numbers belong to another turn.

    The last ``2 * max_turns`` entries are considered. The oldest are then dropped until
    what is left, as it will be sent, fits :data:`_HISTORY_CHAR_BUDGET`; an entry is never
    cut in the middle, so when even the newest is over the budget nothing is kept. Last,
    entries at the front that are answers are dropped, so the history starts with the user.

    :param history: The client's history, oldest first.
    :param max_turns: How many exchanges (a user entry and an assistant entry) to consider.
    :return: The entries to send, oldest first.
    """
    kept = [
        turn.model_copy(update={"content": strip_citations(turn.content)})
        if turn.role == "assistant"
        else turn
        for turn in history[-2 * max_turns :]
    ]
    size = sum(len(turn.content) for turn in kept)
    while kept and size > _HISTORY_CHAR_BUDGET:
        size -= len(kept.pop(0).content)
    while kept and kept[0].role == "assistant":
        kept.pop(0)
    return kept


@dataclass
class TurnDraft:
    """A turn ready for generation: what the service built before the model is called.

    :ivar request: The validated chat request.
    :ivar ctx: The turn's context.
    :ivar kept: The part of the client's history the model is sent.
    :ivar messages: The conversation for the model, ending with this turn's user message.
    :ivar started: The event loop's clock when :meth:`AssistantService.prepare` began.
    :ivar deadline_at: The event loop's clock when the turn runs out of time.
    """

    request: AssistantChatRequest
    ctx: AssistantContext
    kept: list[ChatTurn]
    messages: list[AnyMessage]
    started: float
    deadline_at: float


class AssistantService:
    """Answers one chat turn using the mode configured in ``Settings``.

    The answer is generated by one of two generators, picked once from
    ``assistant_mode``: a direct model call for ``workflow``, an agent for the other two.

    :param settings: Application settings (mode, limits, model name).
    :param chat_model: The chat model that writes the answer.
    """

    def __init__(self, settings: Settings, chat_model: BaseChatModel) -> None:
        """Pick the generator for the configured mode."""
        self._settings = settings
        self._generator: AnswerGenerator = (
            DirectGenerator(chat_model)
            if settings.assistant_mode == "workflow"
            else AgentGenerator(chat_model, settings.assistant_max_tool_calls)
        )

    async def prepare(self, request: AssistantChatRequest, ctx: AssistantContext) -> TurnDraft:
        """Build everything a turn needs before the model is called.

        The documents are searched with the last message alone, not with the history: a
        follow-up that only makes sense with the earlier turns is searched as it stands,
        which is a known limit. The fetching runs under ``assistant_turn_timeout_seconds``,
        so that a caller that streams the answer meets its failures before any byte is sent.

        :param request: The validated chat request.
        :param ctx: Per-turn context (client, retriever, source registry, project).
        :return: The turn, with the messages for the model and the deadline of the whole turn.
        :raises ProjectNotFoundError: If the request names a project the caller cannot see.
        :raises AssistantUpstreamError: If the API answers something unusable while the
            project is fetched.
        :raises AssistantUnavailableError: If a data server is down or the deadline passes
            while fetching.
        """
        started = asyncio.get_running_loop().time()
        mode = self._settings.assistant_mode
        kept = _kept_history(request.history, self._settings.assistant_max_history_turns)
        messages: list[AnyMessage] = [
            HumanMessage(content=turn.content)
            if turn.role == "user"
            else AIMessage(content=turn.content)
            for turn in kept
        ]
        deadline_at = started + self._settings.assistant_turn_timeout_seconds
        try:
            async with asyncio.timeout_at(deadline_at) as deadline:
                parts = [] if mode == "agent" else await self._fetch(request, ctx)
                if mode != "workflow" and ctx.current_project_id is not None:
                    parts.append(f"Current project id: {ctx.current_project_id}")
                messages.append(HumanMessage(content=user_message(parts, request.message)))
        except TimeoutError:
            if not deadline.expired():
                raise
            raise self._timed_out(mode, started) from None
        except UNAVAILABLE_ERRORS as exc:
            raise self._unavailable(exc, mode) from None
        return TurnDraft(request, ctx, kept, messages, started, deadline_at)

    async def answer(
        self, request: AssistantChatRequest, ctx: AssistantContext
    ) -> AssistantChatResponse:
        """Answer one turn in the configured mode.

        The whole turn, fetching and generation, runs under
        ``assistant_turn_timeout_seconds``. A check that fails changes the flags of the
        response and nothing else: the answer is not generated again.

        :param request: The validated chat request.
        :param ctx: Per-turn context (client, retriever, source registry, project).
        :return: The answer, its sources, the tools that ran, the grounding checks, the
            tokens the answer model used and the time the turn took.
        :raises ProjectNotFoundError: If the request names a project the caller cannot see.
        :raises AssistantUpstreamError: If the API answers something unusable while the
            project is fetched.
        :raises AssistantUnavailableError: If a model or data server is down, the answer
            is empty, or the turn outlives its deadline.
        """
        turn = await self.prepare(request, ctx)
        mode = self._settings.assistant_mode
        try:
            async with asyncio.timeout_at(turn.deadline_at) as deadline:
                empty_reason = "empty"
                with tracing_scope(self._settings):
                    try:
                        text, tools_used, usage = await self._generator.generate(
                            turn.messages, ctx, request.message
                        )
                    except CutOffAnswerError:
                        text, tools_used, empty_reason = "", [], "cut_off"
                if not text:
                    raise self._empty_answer(mode, empty_reason)
        except TimeoutError:
            if not deadline.expired():
                raise
            raise self._timed_out(mode, turn.started) from None
        except UNAVAILABLE_ERRORS as exc:
            raise self._unavailable(exc, mode) from None
        return self._finish(turn, Generated(text, tools_used, usage), ttft_ms=None, streamed=False)

    async def stream(self, turn: TurnDraft) -> AsyncGenerator[str | AssistantChatResponse]:
        """Generate a prepared turn's answer, yielding its text as it arrives.

        The `hybrid` and `agent` modes yield no text, only the final response. The time of the first
        piece is the turn's time to first token. The deadline bounds each wait for the model's
        next piece, and the turn as a whole, because it is one point in time.

        :param turn: What :meth:`prepare` built.
        :return: Pieces of answer text, then the response as the last item.
        :raises AssistantUnavailableError: If a model server is down, the answer is empty or
            cut off, or the turn outlives its deadline, after zero or more pieces.
        """
        mode = self._settings.assistant_mode
        loop = asyncio.get_running_loop()
        model_started = loop.time()
        ttft_ms: int | None = None
        generated: Generated | None = None
        empty_reason = "empty"
        items = self._generator.stream(turn.messages, turn.ctx, turn.request.message)
        try:
            with tracing_scope(self._settings):
                while True:
                    # The deadline bounds only the wait for the model's next piece, never the
                    # yield: a timeout that fired while the consumer held a piece would
                    # cancel the consumer instead of this generator.
                    try:
                        async with asyncio.timeout_at(turn.deadline_at) as deadline:
                            item = await anext(items, None)
                    except TimeoutError:
                        if not deadline.expired():
                            raise
                        raise self._timed_out(mode, turn.started) from None
                    except CutOffAnswerError:
                        empty_reason = "cut_off"
                        break
                    if item is None:
                        break
                    if isinstance(item, Generated):
                        generated = item
                    elif item:
                        if ttft_ms is None:
                            ttft_ms = round((loop.time() - model_started) * 1000)
                        yield item
        except UNAVAILABLE_ERRORS as exc:
            raise self._unavailable(exc, mode) from None
        finally:
            await items.aclose()
        if generated is None or not generated.text:
            raise self._empty_answer(mode, empty_reason)
        yield self._finish(turn, generated, ttft_ms=ttft_ms, streamed=True)

    def _finish(
        self, turn: TurnDraft, generated: Generated, *, ttft_ms: int | None, streamed: bool
    ) -> AssistantChatResponse:
        """Check the answer, record the turn and build the response.

        :param turn: What :meth:`prepare` built.
        :param generated: What the generator produced.
        :param ttft_ms: Milliseconds from the model call to the first piece, when streamed.
        :param streamed: Whether the answer was delivered piece by piece.
        :return: The response.
        """
        ctx, text, usage = turn.ctx, generated.text, generated.usage
        sources = ctx.sources.refs()
        citations_valid = check_citations(text, {source.n for source in sources})
        ungrounded = find_ungrounded_numbers(
            text,
            [
                *ctx.sources.texts(),
                *ctx.tool_outputs,
                turn.request.message,
                *(turn_.content for turn_ in turn.kept if turn_.role == "user"),
                *PINNED_NUMBERS,
                *FORMULA_NUMBERS,
            ],
        )
        duration_ms = round((asyncio.get_running_loop().time() - turn.started) * 1000)
        logger.info(
            "Assistant turn answered",
            extra={
                "event": "assistant_turn",
                "mode": self._settings.assistant_mode,
                "model": self._settings.assistant_answer_llm_model,
                "tool_names": generated.tools_used,
                "tool_call_count": len(generated.tools_used),
                "source_count": len(sources),
                "citations_valid": citations_valid,
                "numbers_grounded": not ungrounded,
                "ungrounded_number_count": len(ungrounded),
                "input_tokens": usage.input_tokens,
                "output_tokens": usage.output_tokens,
                "total_tokens": usage.total_tokens,
                "llm_calls": usage.llm_calls,
                "usage_complete": usage.complete,
                "duration_ms": duration_ms,
                "ttft_ms": ttft_ms,
                "streamed": streamed,
            },
        )
        return AssistantChatResponse(
            answer=text,
            sources=sources,
            tools_used=generated.tools_used,
            checks=AnswerChecks(
                citations_valid=citations_valid,
                numbers_grounded=not ungrounded,
                ungrounded_numbers=ungrounded,
            ),
            usage=usage,
            timing=TurnTiming(ttft_ms=ttft_ms, total_ms=duration_ms),
        )

    @staticmethod
    def _timed_out(mode: str, started: float) -> AssistantUnavailableError:
        """Log that the turn outlived its deadline and build the error to raise."""
        duration_ms = round((asyncio.get_running_loop().time() - started) * 1000)
        logger.warning(
            "Assistant turn timed out",
            extra={"event": "assistant_turn_timeout", "mode": mode, "duration_ms": duration_ms},
        )
        return AssistantUnavailableError("the assistant turn ran out of time")

    @staticmethod
    def _unavailable(exc: Exception, mode: str) -> AssistantUnavailableError:
        """Log a server outage by its class name only and build the error to raise."""
        logger.warning(
            "Assistant dependency unavailable",
            extra={
                "event": "assistant_dependency_unavailable",
                "mode": mode,
                "reason": type(exc).__name__,
            },
        )
        return AssistantUnavailableError("a server the assistant needs is unavailable")

    @staticmethod
    def _empty_answer(mode: str, reason: str) -> AssistantUnavailableError:
        """Log that the model gave no answer and build the error to raise."""
        logger.warning(
            "Assistant answer was empty",
            extra={"event": "assistant_empty_answer", "mode": mode, "reason": reason},
        )
        return AssistantUnavailableError("the model gave an empty answer")

    async def _fetch(self, request: AssistantChatRequest, ctx: AssistantContext) -> list[str]:
        """Fetch what the model is shown ahead of the question, in workflow and hybrid modes.

        The documents are searched and every passage is registered as a source. When the
        request names a project, its details and its result are fetched, and in workflow
        mode, which has no tools, its opinions too. A project with no result yet, or with
        no opinions, simply has no such block. The project blocks are written by the same
        functions the tools use, and are kept in ``ctx.tool_outputs`` as grounding for the
        numbers check.

        :param request: The chat request; its message is the search query.
        :param ctx: The turn's context.
        :return: The context blocks, the excerpts first, then the project blocks.
        :raises ProjectNotFoundError: If the API does not show the project to the caller.
        """
        project_blocks: list[str] = []
        project_id = ctx.current_project_id
        if project_id is not None:
            try:
                project = await ctx.client.get_project(project_id)
                result = await ctx.client.get_result(project_id)
                opinions = (
                    await ctx.client.get_opinions(project_id)
                    if self._settings.assistant_mode == "workflow"
                    else []
                )
            except AssistantNotFoundError as exc:
                raise ProjectNotFoundError(f"Project {project_id} not found") from exc
            project_blocks.append(render_project(project))
            if result is not None:
                project_blocks.append(render_context_block([], result))
            if opinions:
                project_blocks.append(render_opinions(opinions))
            ctx.tool_outputs.extend(project_blocks)
        chunks = await ctx.retriever.search(request.message)
        excerpts = render_context_block([(ctx.sources.add(chunk), chunk) for chunk in chunks], None)
        return [*([excerpts] if excerpts else []), *project_blocks]
