"""Answers one assistant chat turn in the configured mode.

The three modes differ in what the model is given and what it may do:

- ``workflow``: the code fetches the documents and, when the request names a project, the
  project, its result and its opinions, and the model makes one call with no tools.
- ``hybrid``: the same, except the opinions, and the model may then call the tools.
- ``agent``: nothing is fetched ahead; the model calls the tools.

The system prompt is :data:`~api.assistant.agent.prompt.SYSTEM_PROMPT`, unchanged, in every
mode. What is fetched goes into the user message, ahead of the question, and when the
question is recognisably Czech or English the message ends with a line that states the answer
language (see :func:`~api.assistant.agent.generation.user_message`).
"""

import asyncio
import logging
import time

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, AnyMessage, HumanMessage

from api.assistant.agent.checks import check_citations, find_ungrounded_numbers, strip_citations
from api.assistant.agent.context import AssistantContext
from api.assistant.agent.generation import (
    AgentGenerator,
    AnswerGenerator,
    CutOffAnswerError,
    DirectGenerator,
    user_message,
)
from api.assistant.agent.prompt import (
    FORMULA_NUMBERS,
    PINNED_NUMBERS,
    render_context_block,
)
from api.assistant.agent.tools import render_opinions, render_project
from api.assistant.agent.tracing import tracing_scope
from api.assistant.errors import AssistantNotFoundError, AssistantUnavailableError
from api.assistant.upstream import UNAVAILABLE_ERRORS
from api.config import Settings
from api.exceptions import ProjectNotFoundError
from api.schemas.assistant import (
    AnswerChecks,
    AssistantChatRequest,
    AssistantChatResponse,
    ChatTurn,
)

logger = logging.getLogger(__name__)

# The most characters of history the model is sent. The answer model's window is 16384
# tokens, and this budget is what keeps the worst case inside it: the history is the part
# of the prompt the client controls, so the fetched context, the message and the answer
# are left room by capping it.
_HISTORY_CHAR_BUDGET = 6000


def _kept_history(history: list[ChatTurn], max_turns: int) -> list[ChatTurn]:
    """Choose the part of the client's history the model is sent.

    The history comes from the client, so an ``assistant`` entry is the user's own input
    like any other: it gives them nothing they could not type directly. Earlier answers
    still go through :func:`~api.assistant.agent.checks.strip_citations`, because their
    ``[n]`` numbers belong to another turn.

    The last ``2 * max_turns`` entries are considered. The oldest are then dropped until
    what is left, as it will be sent, fits :data:`_HISTORY_CHAR_BUDGET`; an entry is never
    cut in the middle, so when even the newest is over the budget nothing is kept. Last,
    entries at the front that are answers are dropped, so the history starts with the user.

    :param history: The client's history, oldest first.
    :param max_turns: How many exchanges (a user entry and an assistant entry) to consider.
    :return: The entries to send, oldest first.
    """
    kept = [
        turn.model_copy(update={"content": strip_citations(turn.content)})
        if turn.role == "assistant"
        else turn
        for turn in history[-2 * max_turns :]
    ]
    size = sum(len(turn.content) for turn in kept)
    while kept and size > _HISTORY_CHAR_BUDGET:
        size -= len(kept.pop(0).content)
    while kept and kept[0].role == "assistant":
        kept.pop(0)
    return kept


class AssistantService:
    """Answers one chat turn using the mode configured in ``Settings``.

    The answer is generated by one of two generators, picked once from
    ``assistant_mode``: a direct model call for ``workflow``, an agent for the other two.

    :param settings: Application settings (mode, limits, model name).
    :param chat_model: The chat model that writes the answer.
    """

    def __init__(self, settings: Settings, chat_model: BaseChatModel) -> None:
        """Pick the generator for the configured mode."""
        self._settings = settings
        self._generator: AnswerGenerator = (
            DirectGenerator(chat_model)
            if settings.assistant_mode == "workflow"
            else AgentGenerator(chat_model, settings.assistant_max_tool_calls)
        )

    async def answer(
        self, request: AssistantChatRequest, ctx: AssistantContext
    ) -> AssistantChatResponse:
        """Answer one turn in the configured mode.

        The whole turn, fetching and generation, runs under
        ``assistant_turn_timeout_seconds``. The documents are searched with the last
        message alone, not with the history: a follow-up that only makes sense with the
        earlier turns is searched as it stands, which is a known limit.

        A check that fails changes the flags of the response and nothing else: the answer
        is not generated again.

        :param request: The validated chat request.
        :param ctx: Per-turn context (client, retriever, source registry, project).
        :return: The answer, its sources, the tools that ran, the grounding checks and the
            tokens the answer model used.
        :raises ProjectNotFoundError: If the request names a project the caller cannot see.
        :raises AssistantUpstreamError: If the API answers something unusable while the
            project is fetched.
        :raises AssistantUnavailableError: If a model or data server is down, the answer
            is empty, or the turn outlives its deadline.
        """
        started = time.monotonic()
        mode = self._settings.assistant_mode
        kept = _kept_history(request.history, self._settings.assistant_max_history_turns)
        messages: list[AnyMessage] = [
            HumanMessage(content=turn.content)
            if turn.role == "user"
            else AIMessage(content=turn.content)
            for turn in kept
        ]
        deadline = asyncio.timeout(self._settings.assistant_turn_timeout_seconds)
        try:
            async with deadline:
                parts = [] if mode == "agent" else await self._fetch(request, ctx)
                if mode != "workflow" and ctx.current_project_id is not None:
                    parts.append(f"Current project id: {ctx.current_project_id}")
                messages.append(HumanMessage(content=user_message(parts, request.message)))
                empty_reason = "empty"
                with tracing_scope(self._settings):
                    try:
                        text, tools_used, usage = await self._generator.generate(
                            messages, ctx, request.message
                        )
                    except CutOffAnswerError:
                        text, tools_used, empty_reason = "", [], "cut_off"
                if not text:
                    logger.warning(
                        "Assistant answer was empty",
                        extra={
                            "event": "assistant_empty_answer",
                            "mode": mode,
                            "reason": empty_reason,
                        },
                    )
                    raise AssistantUnavailableError("the model gave an empty answer")
        except TimeoutError:
            if not deadline.expired():
                raise
            duration_ms = round((time.monotonic() - started) * 1000)
            logger.warning(
                "Assistant turn timed out",
                extra={"event": "assistant_turn_timeout", "mode": mode, "duration_ms": duration_ms},
            )
            raise AssistantUnavailableError("the assistant turn ran out of time") from None
        except UNAVAILABLE_ERRORS as exc:
            logger.warning(
                "Assistant dependency unavailable",
                extra={
                    "event": "assistant_dependency_unavailable",
                    "mode": mode,
                    "reason": type(exc).__name__,
                },
            )
            raise AssistantUnavailableError("a server the assistant needs is unavailable") from None

        sources = ctx.sources.refs()
        citations_valid = check_citations(text, {source.n for source in sources})
        ungrounded = find_ungrounded_numbers(
            text,
            [
                *ctx.sources.texts(),
                *ctx.tool_outputs,
                request.message,
                *(turn.content for turn in kept if turn.role == "user"),
                *PINNED_NUMBERS,
                *FORMULA_NUMBERS,
            ],
        )
        logger.info(
            "Assistant turn answered",
            extra={
                "event": "assistant_turn",
                "mode": mode,
                "model": self._settings.assistant_answer_llm_model,
                "tool_names": tools_used,
                "tool_call_count": len(tools_used),
                "source_count": len(sources),
                "citations_valid": citations_valid,
                "numbers_grounded": not ungrounded,
                "ungrounded_number_count": len(ungrounded),
                "input_tokens": usage.input_tokens,
                "output_tokens": usage.output_tokens,
                "total_tokens": usage.total_tokens,
                "llm_calls": usage.llm_calls,
                "usage_complete": usage.complete,
                "duration_ms": round((time.monotonic() - started) * 1000),
            },
        )
        return AssistantChatResponse(
            answer=text,
            sources=sources,
            tools_used=tools_used,
            checks=AnswerChecks(
                citations_valid=citations_valid,
                numbers_grounded=not ungrounded,
                ungrounded_numbers=ungrounded,
            ),
            usage=usage,
        )

    async def _fetch(self, request: AssistantChatRequest, ctx: AssistantContext) -> list[str]:
        """Fetch what the model is shown ahead of the question, in workflow and hybrid modes.

        The documents are searched and every passage is registered as a source. When the
        request names a project, its details and its result are fetched, and in workflow
        mode, which has no tools, its opinions too. A project with no result yet, or with
        no opinions, simply has no such block. The project blocks are written by the same
        functions the tools use, and are kept in ``ctx.tool_outputs`` as grounding for the
        numbers check.

        :param request: The chat request; its message is the search query.
        :param ctx: The turn's context.
        :return: The context blocks, the excerpts first, then the project blocks.
        :raises ProjectNotFoundError: If the API does not show the project to the caller.
        """
        project_blocks: list[str] = []
        project_id = ctx.current_project_id
        if project_id is not None:
            try:
                project = await ctx.client.get_project(project_id)
                result = await ctx.client.get_result(project_id)
                opinions = (
                    await ctx.client.get_opinions(project_id)
                    if self._settings.assistant_mode == "workflow"
                    else []
                )
            except AssistantNotFoundError as exc:
                raise ProjectNotFoundError(f"Project {project_id} not found") from exc
            project_blocks.append(render_project(project))
            if result is not None:
                project_blocks.append(render_context_block([], result))
            if opinions:
                project_blocks.append(render_opinions(opinions))
            ctx.tool_outputs.extend(project_blocks)
        chunks = await ctx.retriever.search(request.message)
        excerpts = render_context_block([(ctx.sources.add(chunk), chunk) for chunk in chunks], None)
        return [*([excerpts] if excerpts else []), *project_blocks]
